export const foodsData: {
  id: number
  name: string
  brand?: string
  unit: string
  grams: number
  calories: number
  carbs: number
  cafeine: number
}[] = [
  {
    id: 1,
    name: 'Dulce Membrillo',
    unit: '1 lonja',
    grams: 14,
    calories: 39,
    carbs: 10,
    cafeine: 0,
  },
  {
    id: 2,
    name: 'Frugelé',
    brand: 'Ambrosoli',
    unit: '1 unidad',
    grams: 4,
    calories: 14,
    carbs: 3,
    cafeine: 0,
  },
  {
    id: 3,
    name: 'Gel',
    brand: '226ERS',
    unit: '1 Energy Gel',
    grams: 25,
    calories: 75,
    carbs: 18.3,
    cafeine: 0,
  },
  {
    id: 4,
    name: 'Bebida Isotónica',
    brand: 'Isotónica',
    unit: '1 Bebida Isotónica',
    grams: 1,
    calories: 0.24,
    carbs: 0.06,
    cafeine: 0,
  },
  {
    id: 5,
    name: 'Dátiles',
    unit: '1 Unidad',
    grams: 30,
    calories: 24,
    carbs: 6,
    cafeine: 0,
  },
  {
    id: 6,
    name: 'Damascos turcos',
    unit: '1 Unidad',
    grams: 11,
    calories: 9,
    carbs: 2,
    cafeine: 0,
  },
  {
    id: 7,
    name: 'Gel',
    brand: 'Sponser',
    unit: 'Liquid energy plus',
    grams: 70,
    calories: 200,
    carbs: 50,
    cafeine: 50,
  },
  {
    id: 8,
    name: 'Gomitas',
    brand: 'Gu',
    unit: 'Energy Chews',
    grams: 60,
    calories: 180,
    carbs: 44,
    cafeine: 40,
  },
  {
    id: 9,
    name: 'Agua',
    unit: '50 CC',
    grams: 1,
    calories: 0,
    carbs: 0,
    cafeine: 0,
  },
  {
    id: 10,
    name: 'Shot',
    brand: 'Sponser',
    unit: 'Cafeina',
    grams: 0,
    calories: 0,
    carbs: 0,
    cafeine: 200,
  },
  {
    id: 11,
    name: 'Gel',
    brand: '226ers',
    unit: 'High energy gel',
    grams: 76,
    calories: 200,
    carbs: 50,
    cafeine: 160,
  },
  {
    id: 12,
    name: 'Gel',
    brand: 'Stinger',
    unit: 'Gold',
    grams: 34,
    calories: 100,
    carbs: 25,
    cafeine: 0,
  },
  {
    id: 13,
    name: 'Magnesio',
    brand: 'Sponser',
    unit: 'Magnesiu, 375',
    grams: 30,
    calories: 27,
    carbs: 5,
    cafeine: 0,
  },
  {
    id: 14,
    name: 'Gomitas',
    brand: 'Sponser',
    unit: 'Power Gums(10)',
    grams: 75,
    calories: 255,
    carbs: 59,
    cafeine: 150,
  },
  {
    id: 15,
    name: 'Aminoácidos',
    brand: 'Sponser',
    unit: 'BCAA 12500',
    grams: 30,
    calories: 72,
    carbs: 4.6,
    cafeine: 0,
  },
]